<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Logout extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 注销
     */
    public function feed_back(){
        if(empty($_POST['uid']) || !in_array($_POST['client'], $this->client_type_array)) {
            output_error('参数错误1');
        }

       
    }
}