<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Reclass extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        header("Access-Control-Allow-Origin: *");
    }
    //重温课堂首页
    public function index(){

    }

    //重温课堂购买片段页
    public function fragment(){

    }


    //重温课堂购买套餐页
    public function package(){

    }




}