<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Robotroster extends MobileMall
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //机器人认证
    public function auth(){
        $SNNumber = input('post.SNNumber');
        if(empty($SNNumber)){
            output_error('SNNumber参数有误');
        }
        $model_robot = Model("Robot");
        $data = $model_robot->getOne(array('SNNumber'=>$SNNumber,'isdel'=>1));
        output_data($data);
    }

    //获取花名册
    public function roster(){
        $school_id = input('post.school_id');
        if(empty($school_id)){
            output_error('school_id参数有误');
        }
        $model_student = Model("Student");
        $data = $model_student->getAllStudent(array('s_schoolid'=>$school_id));
        output_data($data);
    }

}