<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Robotreport extends MobileMall
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //单个考勤上报
    public function report(){
        $school_id = input('post.school_id');
        if(empty($school_id)){
            output_error('school_id参数有误');
        }
        $model_school = Model("School");
        $schoolInfo = $model_school->getSchoolInfo(array('schoolid'=>$school_id,'isdel'=>1),"schoolid,name");
        if(empty($schoolInfo)){
            output_error('无此学校的信息');
        }
        $student_id = input('post.student_id');
        if(empty($student_id)){
            output_error('student_id参数有误');
        }
        $student_model = Model("Student");
        $studentInfo = $student_model->getStudentInfo(array('s_id'=>$student_id,'s_del'=>1),"s_id,s_name,s_ownerAccount");
        if(empty($studentInfo)){
            output_error('无此学生的信息');
        }
        $class_id = input('post.class_id');
        $videoName = "robot_".$student_id."_".date("YmdHis",time())."_".time().".mp4";
        $video = $this->ioVideo($videoName);
        if($video){
            $data = [
                'school_id' => $school_id,
                'class_id' => $class_id,
                'student_id' => $student_id,
                'uType' => input('post.uType'),
                'ioFlag' => input('post.ioFlag'),
                'ioTime' => input('post.ioTime'),
                'bodyTemp' => input('post.bodyTemp'),
                'SNNumber' => input('post.SNNumber'),
                'ioVideo' => $video,
                'create_time' => time()
            ];
            $report_model = Model("Robotreport");
            $result = $report_model->report_add($data);
            if($result){
                /*$path = "http://".$_SERVER['HTTP_HOST']."/uploads/home/robotvideo/";
                //打卡成功，给学生家长发送短信提醒
                $memberInfo = db("member")->field("member_mobile")->where(array('member_id'=>$studentInfo['s_ownerAccount']))->find();
                if(preg_match('/^0?(13|15|17|18|14)[0-9]{9}$/i', $memberInfo['member_mobile'])){
                    if(input('post.ioFlag')==1){
                        $content = '您的孩子'.date("Y-m-d H:i:s",time()).'已进入学校，请及时关注孩子信息，详情请点击'.$path.$video.'。点击链接可以查看孩子打卡视频画面。';
                    }elseif(input('post.ioFlag')==2){
                        $content = '您的孩子'.date("Y-m-d H:i:s",time()).'已离开学校，请及时关注孩子信息，详情请点击'.$path.$video.'。点击链接可以查看孩子打卡视频画面。';
                    }
                    $sms = new \sendmsg\sdk\SmsApi();
                    $send = $sms->sendSMS($memberInfo['member_mobile'],$content);
                    if(!$send){
                        $this->error('给用户发送短信失败 ');
                    }
                }*/
                output_data("打卡成功");
            }else{
                output_error('上报考勤失败');
            }
        }
    }

    /*
     * 上传打卡视频
     * */
    public function ioVideo($videoName){
        //上传路径
        $uploadimg_path = substr(str_replace("\\","/",$_SERVER['SCRIPT_FILENAME']),'0','-9')."uploads/home/robotvideo/";
        //检查是否有该文件夹，如果没有就创建
        if(!is_dir($uploadimg_path)){
            mkdir($uploadimg_path,0777,true);
        }
        if (!empty($_FILES['ioVideo']['name'])) {
            $upload = move_uploaded_file($_FILES["ioVideo"]["tmp_name"], $uploadimg_path . $videoName);
            if($upload){
                return $videoName;
            }else{
                output_data("上传打卡视频失败");
            }
        }
    }

}