<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Robotreport extends MobileMall
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //单个考勤上报
    public function report(){
        $school_id = input('post.school_id');
        if(empty($school_id)){
            output_error('school_id参数有误');
        }
        $model_school = Model("School");
        $schoolInfo = $model_school->getSchoolInfo(array('schoolid'=>$school_id,'isdel'=>1),"schoolid,name");
        if(empty($schoolInfo)){
            output_error('无此学校的信息');
        }
        $student_id = input('post.student_id');
        if(empty($student_id)){
            output_error('student_id参数有误');
        }
        $student_model = Model("Student");
        $studentInfo = $student_model->getStudentInfo(array('s_id'=>$school_id,'s_del'=>1),"s_id,s_name");
        if(empty($studentInfo)){
            output_error('无此学生的信息');
        }
        $class_id = input('post.class_id');
        $videoName = "robot_".$student_id."_".date("YmdHis",time())."_".time().".mp4";
        $video = $this->ioVideo($videoName);
        if($video){
            $data = [
                'school_id' => $school_id,
                'class_id' => $class_id,
                'student_id' => $student_id,
                'uType' => input('post.uType'),
                'ioFlag' => input('post.ioFlag'),
                'ioTime' => input('post.ioTime'),
                'bodyTemp' => input('post.bodyTemp'),
                'SNNumber' => input('post.SNNumber'),
                'ioVideo' => $video,
                'create_time' => time()
            ];
            $report_model = Model("Robotreport");
            $result = $report_model->report_add($data);
            if($result){
                output_data("打卡成功");
            }else{
                output_error('上报考勤失败');
            }
        }
    }

    /*
     * 上传打卡视频
     * */
    public function ioVideo($videoName){
        //上传路径
        $uploadimg_path = substr(str_replace("\\","/",$_SERVER['SCRIPT_FILENAME']),'0','-9')."uploads/home/robotvideo/";
        //检查是否有该文件夹，如果没有就创建
        if(!is_dir($uploadimg_path)){
            mkdir($uploadimg_path,0777,true);
        }
        if (!empty($_FILES['ioVideo']['name'])) {
            $upload = move_uploaded_file($_FILES["ioVideo"]["tmp_name"], $uploadimg_path . $videoName);
            if($upload){
                return $videoName;
            }else{
                output_data("上传打卡视频失败");
            }
        }
    }

}