<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Robotrecord extends MobileMall
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //获取近7天的打卡记录
    public function record(){
        $student_id = input('post.student_id');
        if(empty($student_id)){
            output_error('student_id参数有误');
        }
        $startTime = strtotime(date("Y-m-d",strtotime ( "-1 week"))." 00:00:00");
        $endTime = time();
        $robot_model = Model('Robotreport');
        $where = "student_id=".$student_id." and ioTime>=".$startTime." and ioTime<=".$endTime;
        $SNNumberInfo = $robot_model->getReportList($where);
        $weekarray=array("星期日","星期一","星期二","星期三","星期四","星期五","星期六");
        $path = "http://".$_SERVER['HTTP_HOST']."/uploads/home/robotvideo/";
        foreach($SNNumberInfo as $k=>$v){
            $SNNumberInfo[$k]['ioDate'] = date("Y-m-d",$v['ioTime']);
            $SNNumberInfo[$k]['ioTime'] = date("H:i:s",$v['ioTime']);
            $SNNumberInfo[$k]['ioVideo'] = $path.$v['ioVideo'];
            if(date("Y-m-d",time()) == date("Y-m-d",$v['ioTime'])){
                $SNNumberInfo[$k]['ioDate'] = "今天";
            }
        }
        foreach($SNNumberInfo as $key=>$item){
            if($item['ioFlag']==1){
                $result[$item['ioDate']]['come'] = $item;
                $result[$item['ioDate']]['come']['ioFlagName'] = "上学签到";
            }
            if(!isset($result[$item['ioDate']]['leave']) && $item['ioFlag']==2){
                $result[$item['ioDate']]['leave'] = $item;
                $result[$item['ioDate']]['leave']['ioFlagName'] = "放学签到";
            }
            $result[$item['ioDate']]['week'] = $weekarray[date("w",$item['ioTime'])];
        }
        $result = !empty($result)?[$result]:[];
        $studentInfo = db('student')->alias('s')
            ->join('__SCHOOL__ sc','sc.schoolid=s.s_schoolid','LEFT')
            ->join('__CLASS__ cl','cl.classid=s.s_classid','LEFT')
            ->field("s_id,s_name,sc.name,cl.classname")
            ->where(array("s_id"=>$student_id))->find();
        $name = $studentInfo['name']."-".$studentInfo['classname']."-".$studentInfo['s_name'];
        $result[1]['name'] = $name;
        output_data($result);
    }

}