<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherchild
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //教孩搜索栏菜单
    public function type(){
        $list=array();
        $list['left']=array(1=>'综合',2=>'最近上传',3=>'评分最高',4=>'评价最多',5=>'价格最高',6=>'价格最低');
        $list['between']=array(7=>'查看免费');
        $pkg = model('Schooltype');
        $condition = array();
        $pkges=$pkg->get_sctype_Lists($condition,'sc_id,sc_type','sc_id asc');
        $ClassType = model('Classtype');
        $Course = model('Course');
        $conditiones = array();
        $course = $Course->get_course_Lists($conditiones, 'co_id,co_type' ,'co_id asc');
        foreach($pkges as $key=>$v){
            $conditionss ='sc_id ='.$v['sc_id'] ;
            $classes= $ClassType->get_classtype_Lists($conditionss, 'cl_id,cl_type');
            $pkges[$key]['class']=$classes;
            $pkges[$key]['course']=$course;
        }
        $list['right']=$pkges;
        $pkgess=$pkg->get_sctype_Lists($condition,'sc_id,sc_type','sc_id asc');
        $conditions=array();
        $class= $ClassType->get_classtype_Lists($conditions, 'cl_id,cl_type');
        $super=array('sc_id'=>'0','sc_type'=>'精品','school'=>$pkgess,'class'=>$class,'course'=>$course);
        array_unshift($list['right'],$super);
        output_data($list);
        output_data($sc_list);
    }

}