<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherdetail
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //教孩单页
    public function detail(){
        $teachchild = model('Teachchild');
        $tid = intval(input('post.tid'));
        $condition['t_id']=$tid;
        $result['data']=$teachchild->getTeachchildInfo($condition,'t_id,t_url,t_title,t_profile');
        $conditions=array();
        $conditions['t_audit']=2;
        $conditions['t_del']=1;
        $lists = $teachchild->getTeachchildList($conditions,'t_id,t_picture,t_title,t_profile', '' ,'rand()',4);
        $result['list']=$lists;
        if($result['data']) {
            output_data($result);
        }else{
            output_error('无此数据');
        }
    }
    //收藏课件
    public function collect(){
        if(!empty($_POST)) {
            $tid = intval(input('post.tid'));
            $member_id = intval(input('post.member_id'));
            $collect = model('Membercollect');
            $condition = array();
            $condition['member_id'] = $member_id;
            $condition['collect_id'] = $tid;
            $condition['type_id'] = 1;
            $res=$collect->getMembercollectInfo($condition);
            if($res){
                output_data(array('res'=>2,'message' => '已经收藏'));
            }else {
                $condition['time'] = time();
                $result = $collect->addMembercollect($condition);
                if ($result) {
                    output_data(array('res'=>1,'message' => '收藏成功'));
                } else {
                    output_error('收藏失败');
                }
            }
        }else{
            output_error('网络错误');
        }
    }
    //添加观看历史记录
    public function addhistory(){
        if(!empty($_POST)) {
            $tid = intval(input('post.tid'));
            $member_id = intval(input('post.member_id'));
            $teachhistory = model('Teachhistory');
            $condition=array();
            $condition['t_tid']=$tid;
            $condition['t_userid']=$member_id;
            $condition['t_del']=1;
            $res=$teachhistory->getTeachhistoryInfo($condition);
            if($res){
                output_data(array('res'=>2,'message' => '今天已有历史记录'));
            }else {
                $condition['t_maketime'] = time();
                $result = $teachhistory->addTeachhistory($condition);
                if ($result) {
                    output_data(array('res'=>1,'message' => '添加成功'));
                } else {
                    output_error('添加失败');
                }
            }
        }else{
            output_error('网络错误');
        }
    }
}