<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


//class Teachertype extends MobileMall
class Teachertype
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //教孩搜索栏菜单
    public function index(){
        //所有分类
        $model_type = model('Teachtype');
        $tmp_list = $model_type->getTreeTypeList(4);
        //一级分类
        $parentType = db('teachtype')->where(array('gc_parent_id'=>0))->select();
        //二级分类
        foreach($parentType as $key=>$item){
            foreach($tmp_list as $k=>$v){
                $newData[$key]['code'] = $item['gc_id'];
                $newData[$key]['name'] = $item['gc_name'];
                if($v['gc_parent_id']==$item['gc_id'] && $v['deep']==2){
                    $newData[$key]['sub'][$k]['code'] = $v['gc_id'];
                    $newData[$key]['sub'][$k]['name'] = $v['gc_name'];
                }
            }
            $newData[$key]['sub'] = array_values($newData[$key]['sub']);
        }

        //三级分类
        foreach($newData as $key=>$item){
            foreach($item['sub'] as $k2=>$v2){
                foreach($tmp_list as $k=>$v){
                    print_r($v);
                    print_r($v2);
                    if($v['gc_parent_id']==$v2['code']){
                        print_r($v);die;
                        $item['sub'][$k2]['sub'][] = $v;
                    }
                }
            }
            //print_r($item);die;
            $newData[$key]['sub'] =  $item['sub'];
        }
        print_r(json_encode($newData));die;
        //四级分类
        foreach($parentType as $key=>$item){
            foreach($item['childTwo'] as $k2=>$v2){
                foreach($v2['childThree'] as $k3=>$v3){
                    foreach($tmp_list as $k=>$v){
                        if($v['gc_parent_id']==$v3['gc_id'] && $v['deep']==4){
                            $v2['childThree'][$k3]['childFour'][] = $v;
                        }
                    }
                }
                $item['childTwo'][$k2]['childThree'] = $v2['childThree'];
            }
            $parentType[$key] =  $item;
        }
        output_data($parentType);
    }

}