<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherdecide extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //判断是否购买 是否收藏
    public function decide(){
        $video_id = intval(input('post.video_id'));
        if(empty($video_id)){
            output_error('video_id参数有误');
        }
        $member_id = intval(input('post.member_id'));
        if(empty($member_id)){
            output_error('member_id参数有误');
        }
        //是否收藏
        $collectinfo = db("membercollect")->where(array('member_id'=>$member_id,'collect_id'=>$video_id,'type_id'=>1,'isdel'=>1))->find();
        if(!empty($collectinfo)){
            $data['collect'] = 1;
        }else{
            $data['collect'] = 0;
        }
        //是否购买
        $orderinfo = db('packagesorderteach')->where(array('buyer_id'=>$member_id,'order_tid'=>$video_id,'order_state'=>20))->order('order_id desc')->limit(1)->find();

        if(!empty($orderinfo)){
            if($orderinfo['order_dieline']>time()){
                $data['buy'] = 1;
            }else{
                $data['buy'] = 0;
            }
        }else{
            $data['buy'] = 0;
        }
        //是否免费
        $free = db('teachchild')->where(array('t_id'=>$video_id))->find();
        if($free['t_price']!=0){
            $data['price'] = $free['t_price'];
        }else{
            $data['price'] = 0;
        }
        output_data($data);
    }

}