<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherchild extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //教孩搜索栏菜单
    public function index(){
        //所有分类
        $model_type = model('Teachtype');
        $tmp_list = $model_type->getTreeTypeList(4);
        //一级分类
        $parentType = db('teachtype')->where(array('gc_parent_id'=>0))->select();
        //二级分类
        foreach($parentType as $key=>$item){
            foreach($tmp_list as $k=>$v){
                if($v['gc_parent_id']==$item['gc_id'] && $v['deep']==2){
                    $parentType[$key]['childTwo'][] = $v;
                }
            }
        }
        //三级分类
        foreach($parentType as $key=>$item){
            foreach($item['childTwo'] as $k2=>$v2){
                foreach($tmp_list as $k=>$v){
                    if($v['gc_parent_id']==$v2['gc_id'] && $v['deep']==3){
                        $item['childTwo'][$k2]['childThree'][] = $v;
                    }
                }
            }
            $parentType[$key]['childTwo'] =  $item['childTwo'];
        }
        //四级分类
        foreach($parentType as $key=>$item){
            foreach($item['childTwo'] as $k2=>$v2){
                foreach($v2['childThree'] as $k3=>$v3){
                    foreach($tmp_list as $k=>$v){
                        if($v['gc_parent_id']==$v3['gc_id'] && $v['deep']==4){
                            $v2['childThree'][$k3]['childFour'][] = $v;
                        }
                    }
                }
                $item['childTwo'][$k2]['childThree'] = $v2['childThree'];
            }
            $parentType[$key] =  $item;
        }
        $data = array();
        $data['navigate'] = [
            "subsume" => ["name"=>"综合","child"=>["综合","价格最高","价格最低"]],
            'free' => ["name"=>"查看免费"],
            'fees' => ["name"=>"查看付费"],
            "select" => ['name'=>"筛选"]
        ];
        $data['categorize'] = $parentType;
        $data['categorize'][] = array("gc_name"=>"推荐","childTwo"=>[]);
        //视频价格范围
        $pkg = model('pkgs');
        $conditions = array();
        $conditions['pkg_type']= 3 ;
        $pkg_list = $pkg->getPkgLists($conditions,'pkg_id,pkg_price','pkg_price asc');
        $data['price'] = $pkg_list;
        $res[] = $data;
        output_data($res);
    }

    //教孩列表页面
    public function lists(){
        $teachchild = model('Teachchild');
        $condition = array();

        if(input('post.type')) {
            $condition['t_type'] = input('post.type');
        }
        if(input('post.type2')){
            $condition['t_type2'] = input('post.type2');
        }
        if(input('post.type3')){
            $condition['t_type3'] = input('post.type3');
        }
        if(input('post.type4')){
            $condition['t_type4'] = input('post.type4');
        }
        if(input('post.recommend')&&input('post.recommend')==2){//推荐
            $condition['t_recommend'] = input('post.recommend');
        }
        if(input('post.subsume')&&input('post.subsume')==1){//综合
            $order='t_maketime desc';
        }
        if(input('post.price_desc')){
            $order='t_price desc,t_id desc';
        }
        if(input('post.price_asc')){
            $order='t_price asc,t_id desc';
        }
        if(empty($order)){
            $order = "t_id desc";
        }
        if(input('post.price_free')){
            $condition['t_price']=0;
        }
        if(input('post.price_fees')){
            $condition['t_price'] = array('neq',0);
        }
        $list = $teachchild->getTeachchildList($condition,'t_id,t_url,t_videoimg,t_picture,t_title,t_profile,t_price,t_userid,t_author', '' ,$order);
        if($list){
            output_data($list);
        }else{
            $list = [];
            output_data($list);
        }
    }

    //我的上传
    public function myUpload(){
        $teachchild = model('Teachchild');
        $condition = array();
        $condition['t_userid'] = 1;
        if(input('post.status')){
            if(input('post.status')==3){
                $condition['t_audit'] = 3;
            }elseif(input('post.status')==1){
                $condition['t_audit'] = array('between',array(1,2));
            }
        }else{
            $condition['t_audit'] = array('between',array(1,2));
        }
        $list = $teachchild->getTeachchildList($condition);
        output_data($list);
    }

    //我的视频/我的订单
    public function myVideos(){
        $member_id = input('post.member_id');
        $result = db('packagesorderteach')->field("order_id,order_sn,order_name,order_tid,order_dieline,add_time,payment_time,order_amount")->where(array('delete_state'=>0,'buyer_id'=>$member_id))->order('add_time',desc)->select();
        foreach($result as $k=>$v){
            $result[$k]['date'] = date("Y-m-d",$v['add_time']);
            if(date("Y-m-d",time()) == date("Y-m-d",$v['add_time'])){
                $result[$k]['date'] = "今天";
            }
            $videoinfo = db('teachchild')->where(array('t_id'=>$v['order_tid']))->find();
            $result[$k]['title'] = $videoinfo['t_title'];
            $result[$k]['videoimg'] = $videoinfo['t_videoimg'];
            $result[$k]['videourl'] = $videoinfo['t_url'];
            $result[$k]['author'] = $videoinfo['t_author'];
            $result[$k]['order_dieline'] = date("Y-m-d H:i:s",$v['order_dieline']);
            $result[$k]['payment_time'] = date("Y-m-d H:i:s",$v['payment_time']);
        }
        foreach($result as $key=>$item){
            $data[$item['date']][] = $item;
        }
        $data = isset($data)?[$data]:[];
        output_data($data);
    }

}