<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherchild
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //教孩搜索栏菜单
    public function type(){
        $list=array();
        $list['left']=array(1=>'综合',2=>'最近上传',3=>'评分最高',4=>'评价最多',5=>'价格最高',6=>'价格最低');
        $list['between']=array(7=>'查看免费');
        $pkg = model('Schooltype');
        $condition = array();
        $pkges=$pkg->get_sctype_Lists($condition,'sc_id,sc_type','sc_id asc');
        $ClassType = model('Classtype');
        $Course = model('Course');
        $conditiones = array();
        $course = $Course->get_course_Lists($conditiones, 'co_id,co_type' ,'co_id asc');
        foreach($pkges as $key=>$v){
            $conditionss ='sc_id ='.$v['sc_id'] ;
            $classes= $ClassType->get_classtype_Lists($conditionss, 'cl_id,cl_type');
            $pkges[$key]['class']=$classes;
            $pkges[$key]['course']=$course;
        }
        $list['right']=$pkges;
        $pkgess=$pkg->get_sctype_Lists($condition,'sc_id,sc_type','sc_id asc');
        $conditions=array();
        $class= $ClassType->get_classtype_Lists($conditions, 'cl_id,cl_type');
        $super=array('sc_id'=>'0','sc_type'=>'精品','school'=>$pkgess,'class'=>$class,'course'=>$course);
        array_unshift($list['right'],$super);
        output_data($list);
    }
    //教孩列表页面
    public function list(){
        $teachchild = model('Teachchild');
        $condition = array();
        $condition['t_audit']=2;
        $condition['t_del']=1;
        if(!empty($_POST['supreme'])) {
            $condition['t_supreme']=1;
        }
        if(!empty($_POST['scid'])) {
            $condition['t_scid']=intval(input('post.scid'));
        }
        if(!empty($_POST['classid'])) {
            $condition['t_classid']=intval(input('post.classid'));
        }
        if(!empty($_POST['courseid'])) {
            $condition['t_courseid']=intval(input('post.courseid'));
        }
        if(!empty($_POST['left'])) {
            $order=intval(input('post.left'));
            if($order==2){
                $order='t_id desc';
            }else if($order==5){
                $order='t_price desc';
            }else if($order==6){
                $order='t_price asc';
            }
        }else{
            $order='t_id desc';
        }
        if(!empty($_POST['between'])) {
            $condition['t_price']=0;
        }
        $list = $teachchild->getTeachchildList($condition,'t_id,t_picture,t_title,t_profile,t_price,t_userid', '' ,$order);
        foreach ($list as $k=>$v){
            $conditions=array();
            $conditions['member_id']=$v['t_userid'];
            $model_member = Model('member');
            $res=$model_member->getMemberInfo($conditions);
            $list[$k]['member_nickname'] = $res['member_nickname'];
        }
        if($list){
            output_data($list);
        }else{
            output_error('暂无数据');
        }
    }
}