<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherdetail extends MobileMall
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //教孩视频详情页
    public function detail(){
        $teachchild = model('Teachchild');
        $tid = intval(input('post.t_id'));
        if(empty($tid)){
            output_error('t_id参数有误');
        }
        $result[]['data'] = $teachchild->getTeachchildInfo(array('t_id'=>$tid));
        $conditions = array();
        $conditions['t_audit'] = 3;
        $conditions['t_del'] = 1;
        $conditions['t_type'] = $result[0]['data']['t_type'];
        $conditions['t_id'] = array('neq',$result[0]['data']['t_id']);
        $result[]['lists'] = $teachchild->getTeachchildList($conditions,'t_id,t_url,t_videoimg,t_title,t_profile,t_author', '' ,'t_maketime desc',4);
        if($result) {
            output_data($result);
        }else{
            output_error('无此视频');
        }
    }

}