<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherupload
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //上传视频课件下拉列表
    public function select(){
        $list=array();
        $ClassType = model('Classtype');
        $condition = array();
        $class=$ClassType->get_classtype_Lists($condition, 'cl_id,cl_type');
        $list['class']=$class;
        $Course = model('Course');
        $conditiones = array();
        $course = $Course->get_course_Lists($conditiones, 'co_id,co_type' ,'co_id asc');
        $list['course']=$course;
        $pkg = model('pkgs');
        $conditions = array();
        $conditions['pkg_type']= 3 ;
        $pkg_list = $pkg->getPkgLists($conditions,'pkg_id,pkg_price','pkg_id desc');
        $list['pkg']=$pkg_list;
        output_data($list);
    }
    //上传课件提交
    public function addcourse(){
        $member_id = intval(input('post.member_id'));
        $where = ' member_id = "'.$member_id.'"';
        $member_identity = db('member')->field('member_identity')->where($where)->find();
        if($member_identity['member_identity']!=2){
            output_error('该会员不属于教师，无法上传课件');
        }
        if(!empty($_POST)) {
            $teachchild = model('Teachchild');
            $condition = array();
            $condition['t_url'] = trim(input('post.url'));
            $condition['t_picture'] = trim(input('post.picture'));
            $condition['t_title'] = trim(input('post.title'));
            $condition['t_profile'] = trim(input('post.profile'));
            $condition['t_classid'] = intval(input('post.classid'));
            $condition['t_courseid'] = intval(input('post.courseid'));
            $condition['t_price'] = trim(input('post.price'));
            $condition['t_userid']=$member_id;
            $condition['t_maketime'] = time();
            $condition['t_audit'] = 1;
            $condition['t_del'] = 1;
            $condition['t_supreme'] = 1;
            $ClassType = model('Classtype');
            $cl_id=input('post.classid');
            $class=$ClassType->getOneById($cl_id);
            $condition['t_scid']=$class['sc_id'];
            if (empty($condition['t_url'])) output_error('上传课件不能为空');
            if (empty($condition['t_picture'])) output_error('上传封面不能为空');
            if (empty($condition['t_title'])) output_error('标题不能为空');
            if (empty($condition['t_profile'])) output_error('简介不能为空');
            if (empty($condition['t_price'])) output_error('价格不能为空');
            $result=$teachchild->addTeachchild($condition);
            if($result){
                output_data(array('message'=>'上传成功'));
            }else{
                output_error('上传失败');
            }
        }else{
            output_error('网络错误');
        }
    }
}