<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teacherupload
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //上传视频课件下拉列表
    public function select(){
        $list=array();


        output_data($list);
        output_data($sc_list);
    }
}