<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


//class Teacherdecide extends MobileMember
class Teacherdecide
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //判断是否购买 是否收藏
    public function decide(){
        $video_id = intval(input('post.video_id'));
        if(empty($video_id)){
            output_error('video_id参数有误');
        }
        $video_id = intval(input('post.video_id'));
        if(empty($video_id)){
            output_error('video_id参数有误');
        }
        $teachchild = model('Teachchild');

        $result[]['data'] = $teachchild->getTeachchildInfo(array('t_id'=>$tid));
        $conditions = array();
        $conditions['t_audit'] = 3;
        $conditions['t_del'] = 1;
        $conditions['t_type'] = $result[0]['data']['t_type'];
        $conditions['t_id'] = array('neq',$result[0]['data']['t_id']);
        $result[]['lists'] = $teachchild->getTeachchildList($conditions,'t_id,t_url,t_videoimg,t_title,t_profile,t_author', '' ,'t_maketime desc',4);
        if($result) {
            output_data($result);
        }else{
            output_error('无此视频');
        }
    }

}