<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Teachercollect extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //课件收藏列表列表
    public function lists(){
        $member_id = intval(input('post.member_id'));
        if(empty($member_id)){
            output_error('member_id参数有误');
        }
        $collect = model('Membercollect');
        $condition=array();
        $condition['member_id'] = $member_id;
        $condition['isdel'] = 1;
        $condition['type_id'] = 1;
        $result = $collect->getMembercollectList($condition);
        foreach($result as $k=>$v){
            $result[$k]['date'] = date("Y-m-d",$v['time']);
            if(date("Y-m-d",time()) == date("Y-m-d",$v['time'])){
                $result[$k]['date'] = "今天";
            }
            $videoinfo = db('teachchild')->where(array('t_id'=>$v['collect_id']))->find();
            $result[$k]['title'] = $videoinfo['t_title'];
            $result[$k]['profile'] = $videoinfo['t_profile'];
            $result[$k]['price'] = $videoinfo['t_price'];
            $result[$k]['videoimg'] = $videoinfo['t_videoimg'];
            $result[$k]['videourl'] = $videoinfo['t_url'];
            $result[$k]['author'] = $videoinfo['t_author'];
        }
        foreach($result as $key=>$item){
            $data[$item['date']][] = $item;
        }
        $datas = !empty($data) ? [$data] : $data;
        output_data($datas);
    }

    //收藏课件
    public function collect(){
        $tid = intval(input('post.tid'));
        $member_id = intval(input('post.member_id'));
        if(empty($tid) || empty($member_id)){
            output_error('参数有误');
        }
        $condition = array();
        $condition['member_id'] = $member_id;
        $condition['collect_id'] = $tid;
        $condition['type_id'] = 1;
        $condition['isdel'] = 1;
        $collect = model('Membercollect');
        $res = $collect->getMembercollectInfo($condition);
        $condition['time'] = time();
        if($res){
            $result = $collect->editMembercollect(array('id'=>$res['id']),$condition);
        }else {
            $result = $collect->addMembercollect($condition);
        }
        if ($result) {
            output_data([array('data'=>"收藏成功")]);
        } else {
            output_error('收藏失败');
        }
    }

    //取消收藏
    public function delcollect(){
        $all = intval(input('post.all'));//全部取消
        $ids = input('post.ids');//多个取消  逗号分隔
        $userid = intval(input('post.member_id'));
        if(empty($ids) || empty($userid)){
            output_error('参数有误');
        }
        if($all==1){
            $where = "member_id={$userid} and isdel=1 and type_id=1";
        }else{
            $where = "member_id={$userid} and type_id=1 and id in ({$ids})";
        }
        $collect = model('Membercollect');
        $result = $collect->editMembercollect($where,array('isdel'=>2));
        if ($result) {
            output_data([array('data'=>"取消成功")]);
        } else {
            output_error('取消失败');
        }
    }

}